# Generated by Django 3.2.16 on 2022-11-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
